version: "3"
services:
  eureka:
    #    image: organization-service
    #build: ./eurekaDiscovery_service
    image: forest_microservices-eureka
    container_name: discoveryService
    ports:
      - "8761:8761"
    networks:
      - s4g-network
    depends_on:
      - custommysql
    healthcheck:
      test: "CMD-SHELL curl -f http://localhost:8761/health || exit 1"
      interval: 10s
      timeout: 3s
      retries: 5


  report:
    #    image: site-service
    #build: ./report_service
    image: forest_microservices-report
    container_name: reportService
    ports:
      - "8082:8082"
    networks:
      - s4g-network
    depends_on:
      - custommysql
      - eureka




  auth:
    #    image: auth
    #build: ./user_authentication_service
    image: forest_microservices-auth
    container_name: authService
    ports:
      - "8081:8081"
    networks:
      - s4g-network
    depends_on:
      - custommysql
      - eureka

  management:
    #    image: management
    #build: ./user_managemenet_service
    image: forest_microservices-management
    container_name: managementService
    ports:
      - "8086:8086"
    networks:
      - s4g-network
    depends_on:
      - custommysql
      - eureka

  gateway:
     image: forest_microservices-gateway
     #build: ./gateway_service
     container_name: gateway
     ports:
       - "8088:8088"
     networks:
       - s4g-network
     depends_on:
       - custommysql
       - eureka
       - auth
       - management
       - report

  custommysql:
    image: mysql:8
    container_name: custommysql
    networks:
      - s4g-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=production_testing
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
      interval: 10s
      retries: 5

networks:
  s4g-network:
    driver: bridge